module Jekyll
  class TagPageGenerator < Generator
    safe true
    priority :low
    
    def generate(site)
      return if site.tags.empty?
      
      # Generate halaman untuk setiap tag
      site.tags.each do |tag_name, posts|
        generate_tag_page(site, tag_name, posts)
      end
    end
    
    private
    
    def generate_tag_page(site, tag_name, posts)
      # Buat slug untuk URL
      tag_slug = tag_name.downcase
                        .gsub(' ', '-')
                        .gsub(/[^a-z0-9\-]/, '')
                        .squeeze('-')
                        .chomp('-')
      
      # Path untuk halaman tag
      tag_dir = File.join('tag', tag_slug)
      
      # Buat halaman HTML
      page = PageWithoutAFile.new(site, site.source, tag_dir, 'index.html')
      
      # Set metadata
      page.data = {
        'layout' => 'tag_page',
        'title' => "Tag: #{tag_name}",
        'tag_name' => tag_name,
        'tag_slug' => tag_slug,
        'posts' => posts,
        'permalink' => "/tag/#{tag_slug}/",
        'description' => "Halaman tag #{tag_name}. Total #{posts.size} postingan."
      }
      
      # Set content (akan diisi oleh layout)
      page.content = "<!-- Content generated by layout -->"
      
      # Tambahkan ke site
      site.pages << page
    end
  end
  
  class PageWithoutAFile < Page
    def initialize(site, base, dir, name)
      @site = site
      @base = base
      @dir  = dir
      @name = name
      
      self.process(name)
      self.data ||= {}
      
      # Read YAML front matter
      self.read_yaml(File.join(base, '_layouts'), 'default.html')
    end
  end
end
