name: Sync Blogger Feed to Jekyll

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Blogger Feed
        run: |
          curl -s --max-time 60 "https://www.xcelebgram.my.id/feeds/posts/default?start-index=1&max-results=9999&alt=json" -o blogger_feed.json

      - name: Convert JSON to Jekyll Posts
        run: |
          mkdir -p _posts
          jq -r '.feed.entry[] | 
            {
              date: (.published.$t | gsub("T.*"; "")),
              slug: (.title.$t | gsub("[^a-zA-Z0-9]+"; "-") | ascii_downcase),
              image: (.media$thumbnail.url // "https://via.placeholder.com/600"),
              title: .title.$t,
              content: .content.$t
            } | 
            "---\nlayout: post\ntitle: \"" + .title + "\"\nauthor: admin\nimage: \"" + .image + "\"\n---\n\n" + .content' blogger_feed.json | while read -r post; do
              filename="_posts/$(jq -r '.date + "-" + .slug + ".html"' <<< "$post")"
              echo "$post" > "$filename"
            done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "Update Blogger Feed to Jekyll Format" || exit 0
          git push
