name: Sync Blogger Feed to Jekyll Format

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Blogger Feed Availability
        run: |
          if curl --head --silent --fail "https://www.xcelebgram.my.id/feeds/posts/default?start-index=1&max-results=1&alt=json"; then
            echo "Feed is available"
          else
            echo "Feed is NOT available"
            exit 1
          fi

      - name: Fetch Blogger Feed
        run: |
          curl -A "Mozilla/5.0" -s --max-time 60 "https://www.xcelebram.my.id/feeds/posts/default?start-index=1&max-results=9999&alt=json" > blogger_feed.json || wget -O blogger_feed.json "https://www.xcelebram.my.id/feeds/posts/default?start-index=1&max-results=9999&alt=json"

      - name: Convert JSON to Jekyll Format
        run: |
          mkdir -p _posts
          jq -r '.feed.entry[] | 
            (.published.$t | sub("T.*";"")) as $date |
            (.published.$t | sub("Z";"") | sub("T";" ")) as $datetime |
            (.title.$t | gsub("[^a-zA-Z0-9]+"; "-") | ascii_downcase) as $slug |
            ((.category | map(.term)) // ["uncategorized"]) as $categories |
            ((.media$thumbnail.url)? // "https://via.placeholder.com/600") as $image |
            ((.link[] | select(.rel=="alternate") | .href) // "") as $permalink |
            ("---\nlayout: post\ntitle: \"" + .title.$t + "\"\nauthor: admin\ncategories: " + ($categories | tostring) + "\nimage: \"" + $image + "\"\n---\n\n" + .content.$t) as $content |
            ("mkdir -p _posts && echo '" + $content + "' > _posts/" + $date + "-" + $slug + ".html")' blogger_feed.json | bash

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "Update Blogger Feed to Jekyll Format" || exit 0
          git push
