name: Sync Blogger Feed to Jekyll

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Blogger Feed
        run: |
          curl -s "https://www.xcelebram.my.id/feeds/posts/default?start-index=1&max-results=9999&alt=json" > blogger_feed.json

      - name: Convert JSON to Jekyll Format
        run: |
          mkdir -p _posts
          jq -r '
            .feed.entry[]? | 
            (.title.$t // "Untitled") as $title |
            (.published.$t | sub("T.*";"")) as $date |
            (.updated.$t | sub("T"; " ") | sub("Z"; "")) as $datetime |
            (.category? | map(.term) | join(", ") // "uncategorized") as $categories |
            (.media$thumbnail?.url // "https://via.placeholder.com/600") as $image |
            (.content.$t // "No content available") as $content |
            (.link[] | select(.rel == "alternate") | .href) as $permalink |
            ($title | gsub("[^a-zA-Z0-9]+"; "-") | ascii_downcase) as $slug |
            "_posts/" + $date + "-" + $slug + ".html" as $filename |
            "---\nlayout: post\ntitle: \"" + $title + "\"\nauthor: admin\ncategories: [" + $categories + "]\nimage: \"" + $image + "\"\n---\n\n" + $content | 
            { filename: $filename, content: . }' blogger_feed.json > parsed_feed.json

          cat parsed_feed.json | jq -c '.[]' | while read -r post; do
            filename=$(echo "$post" | jq -r '.filename')
            content=$(echo "$post" | jq -r '.content')
            echo "$content" > "$filename"
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add _posts/
          git commit -m "Update Blogger Feed to Jekyll" || exit 0
          git push
